/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inputrebind;
import inputrebind.AppFrame;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());
        new AppFrame();
    }
}
